# Generated by Django 3.1.1 on 2021-05-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('map_api', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('message', models.CharField(max_length=256)),
                ('calendar_api', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'api_settings',
            },
        ),
    ]
