# Generated by Django 3.1.14 on 2024-04-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0002_auto_20210427_1305'),
        ('Patient', '0003_auto_20210427_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('morning_dosage', models.CharField(max_length=100)),
                ('afternoon_dosage', models.CharField(max_length=100)),
                ('night_dosage', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
            options={
                'db_table': 'prescriction',
            },
        ),
    ]
