# Generated by Django 3.1.1 on 2021-04-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=6)),
                ('birthdate', models.DateField(null=True)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=7)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=3)),
                ('blood_pressure', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.category')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
